name: Build app
on: [push]
jobs:
  Build-Apk:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      #- run: git config --system core.longpaths true
      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '1.22.6'
          channel: 'stable'
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r20b
          add-to-path: false
          local-cache: true
      - name: Write local.properties
        run: echo "ndk.dir=${{ steps.setup-ndk.outputs.ndk-path }}" > android/local.properties
      - name: Build
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: echo -n $KEY_JKS | base64 --decode > android/key.jks && flutter pub get && flutter build apk --release
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
